"""
Generate difficult Data Communication MCQ questions and write to questions.json.
Reads lecture_content.json for reference; questions are embedded in QUESTIONS list.
"""
import json
import random
from pathlib import Path

from lecture5_questions import LECTURE5_QUESTIONS

LECTURE_CONTENT_PATH = Path(__file__).parent / "lecture_content.json"
OUTPUT_PATH = Path(__file__).parent / "questions.json"


def load_lecture_reference():
    """Load lecture content JSON for reference (not used to generate questions)."""
    if LECTURE_CONTENT_PATH.exists():
        with open(LECTURE_CONTENT_PATH, encoding="utf-8") as f:
            return json.load(f)
    return {}


def shuffle_options(options, correct_index):
    """Shuffle options and return new list with updated correct index."""
    indexed = list(enumerate(options))
    random.shuffle(indexed)
    new_options = [opt for _, opt in indexed]
    new_correct = next(i for i, (orig, _) in enumerate(indexed) if orig == correct_index)
    return new_options, new_correct


def prepare_questions(seed=42):
    """Assign IDs and shuffle options for each question."""
    random.seed(seed)
    prepared = []
    for idx, q in enumerate(QUESTIONS, start=1):
        opts, correct = shuffle_options(q["options"], q["correct"])
        prepared.append({
            "id": idx,
            "lecture": q["lecture"],
            "question": q["question"],
            "options": opts,
            "correct": correct,
            "explanation": q["explanation"],
        })
    return prepared


def main():
    _ = load_lecture_reference()
    questions = prepare_questions()
    expected = len(QUESTIONS)
    assert len(questions) == expected, f"Expected {expected} questions, got {len(questions)}"
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)
    print(len(questions))


QUESTIONS = [
    {
        "lecture": "Lecture 1",
        "question": "A video conferencing session exhibits packets arriving at 30 ms, 45 ms, 28 ms, and 52 ms intervals despite uniform 30 ms generation. Which data communication characteristic is primarily violated?",
        "options": ["Jitter", "Accuracy", "Delivery", "Timeliness alone without variation concern"],
        "correct": 0,
        "explanation": "Jitter is the variation in packet arrival time; uneven delays degrade real-time audio/video quality even when data eventually arrives.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Data delivered to the wrong workstation but uncorrupted violates which fundamental characteristic first?",
        "options": ["Delivery", "Accuracy", "Timeliness", "Jitter"],
        "correct": 0,
        "explanation": "Delivery requires data reach the intended device only; corruption-free wrong-destination data still fails delivery.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Real-time transmission in the lecture context specifically emphasizes:",
        "options": ["Delivering data as produced, in order, without significant delay", "Maximizing throughput regardless of order", "Ensuring zero bit errors only", "Compressing all packets before send"],
        "correct": 0,
        "explanation": "Timeliness for video/audio means in-order, low-latency delivery matching production rate.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which quality factor measures time delay between transmission and receipt?",
        "options": ["Latency", "Bandwidth", "Error rate", "Jitter"],
        "correct": 0,
        "explanation": "Latency is end-to-end delay; high latency slows interactive communication.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Higher signal-to-noise ratio generally indicates:",
        "options": ["Clearer, more reliable communication", "Higher latency", "Lower bandwidth", "Increased jitter"],
        "correct": 0,
        "explanation": "Higher SNR means signal dominates noise, improving clarity and reliability.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Message size and complexity are classified in the lecture as:",
        "options": ["Internal factors affecting communication quality", "External pathway factors", "Protocol layer functions", "Physical topology properties"],
        "correct": 0,
        "explanation": "Internal factors relate to message nature; size and complexity are internal.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Simultaneous messages on a shared network path are an example of:",
        "options": ["An external factor affecting quality", "An internal message factor", "A presentation layer concern", "A MAC addressing issue"],
        "correct": 0,
        "explanation": "External factors include pathway quality and concurrent network traffic.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Without a protocol, two connected devices:",
        "options": ["May be connected but cannot communicate meaningfully", "Automatically use TCP/IP", "Share MAC addresses", "Operate at application layer"],
        "correct": 0,
        "explanation": "Protocol is the agreed rule set; connection alone does not enable understanding.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which is NOT one of the five components of a data communication system per the lecture?",
        "options": ["Router", "Message", "Sender", "Transmission medium"],
        "correct": 0,
        "explanation": "The five components are message, sender, receiver, transmission medium, and protocol.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Numbers in data communication are represented by:",
        "options": ["Direct binary bit patterns, not ASCII text encoding", "ASCII codes exclusively", "Analog waveforms only", "Hexadecimal MAC addresses"],
        "correct": 0,
        "explanation": "Unlike text, numbers convert directly to binary for mathematical operations.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Audio is described as continuous rather than discrete because:",
        "options": ["It varies continuously over time unlike discrete text or pixel grids", "It uses only analog hubs", "It cannot be digitized", "It requires application layer gateways"],
        "correct": 0,
        "explanation": "Audio is inherently continuous; digitization samples it but nature differs from discrete text/images.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A NIC MAC address is typically:",
        "options": ["A 48-bit manufacturer-assigned identifier in hexadecimal", "A 32-bit IPv4 address", "A protocol port number", "A 128-bit IPv6 prefix"],
        "correct": 0,
        "explanation": "MAC addresses are 48-bit hardware identifiers, usually shown in hex.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Software configuration of IP address, subnet mask, and default gateway on a NIC occurs at:",
        "options": ["Network layer configuration (logical addressing), not MAC assignment", "Physical layer only", "Application layer exclusively", "MAC manufacturer ROM only"],
        "correct": 0,
        "explanation": "IP settings are logical network configuration layered above the hardware MAC.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which device operates exclusively at OSI Layer 1 (Physical)?",
        "options": ["Repeater", "Switch", "Bridge", "Router"],
        "correct": 0,
        "explanation": "Repeaters regenerate signals at the physical layer without framing or addressing logic.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A hub differs from a switch primarily because a hub:",
        "options": ["Broadcasts packets to all ports without filtering or intelligent forwarding", "Operates at network layer", "Translates between protocol suites", "Segments collision domains per MAC table"],
        "correct": 0,
        "explanation": "Hubs are multiport repeaters flooding all ports; no selective forwarding.",
    },
    {
        "lecture": "Lecture 1",
        "question": "An active hub differs from a passive hub because an active hub:",
        "options": ["Has its own power supply and can clean, boost, and relay signals", "Collects wiring only without amplification", "Operates at Layer 3", "Filters frames by MAC address"],
        "correct": 0,
        "explanation": "Active hubs amplify and regenerate; passive hubs merely relay without boosting.",
    },
    {
        "lecture": "Lecture 1",
        "question": "At which OSI layer does a switch primarily operate?",
        "options": ["Data Link Layer (Layer 2)", "Physical Layer", "Network Layer", "Application Layer"],
        "correct": 0,
        "explanation": "Switches forward frames using MAC addresses at Layer 2.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A bridge is primarily used to:",
        "options": ["Connect network segments at Layer 2 and reduce congestion within LANs", "Translate application protocols between WANs", "Regenerate bits on a single cable only", "Route packets using IP addresses globally"],
        "correct": 0,
        "explanation": "Bridges interconnect LAN segments at the data link layer.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A gateway operates at OSI Layer 7 primarily to:",
        "options": ["Translate protocols and data formats between dissimilar networks", "Forward frames by MAC address", "Amplify attenuated electrical signals", "Assign DHCP leases"],
        "correct": 0,
        "explanation": "Gateways perform application-layer protocol translation between heterogeneous systems.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Routers use which addressing scheme for inter-network forwarding?",
        "options": ["IP addresses at the Network Layer (Layer 3)", "MAC addresses only", "Port numbers exclusively", "Physical cable identifiers"],
        "correct": 0,
        "explanation": "Routers forward packets between networks using logical IP addressing.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which network device can perform NAT and VPN functions per the lecture?",
        "options": ["Router", "Passive hub", "Repeater", "Unmanaged switch"],
        "correct": 0,
        "explanation": "Routers may filter traffic, perform NAT, and provide VPN connectivity.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Wi-Fi NIC standards mentioned include 802.11n, 802.11ac, and:",
        "options": ["802.11ax", "802.3ab", "802.1Q", "802.15.1 only"],
        "correct": 0,
        "explanation": "802.11ax is a Wi-Fi standard; 802.3 relates to Ethernet wired.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Ethernet NIC speeds cited include 10 Mbps, 100 Mbps, and:",
        "options": ["1 Gbps", "56 Kbps", "10 Gbps only as minimum", "512 Kbps"],
        "correct": 0,
        "explanation": "Lecture lists 10, 100 Mbps, and 1 Gbps as common Ethernet NIC speeds.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Accuracy in data communication means:",
        "options": ["Data must arrive unchanged from what was sent", "Data must arrive quickly only", "Data must reach any device on the subnet", "Packets must be equal size"],
        "correct": 0,
        "explanation": "Accuracy requires uncorrupted data; altered transmission renders data unusable.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Bandwidth in quality of communication refers to:",
        "options": ["Data transmittable per unit time over a channel", "Physical cable length", "Number of network devices", "Protocol header size"],
        "correct": 0,
        "explanation": "Bandwidth is capacity over time, not distance or device count.",
    },
    {
        "lecture": "Lecture 1",
        "question": "High error rate during transmission most directly threatens:",
        "options": ["Accuracy and usability of received data", "Only physical layer naming", "Application layer GUI design", "Star topology geometry"],
        "correct": 0,
        "explanation": "Errors corrupt data, undermining accuracy and information integrity.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Interference as a quality factor results in:",
        "options": ["Data loss or corruption on the channel", "Increased MAC address length", "Mandatory full-duplex mode", "OSI layer reduction"],
        "correct": 0,
        "explanation": "Interference disrupts signals, causing loss or corruption.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Devices that originate messages include PCs and servers; devices that direct messages include:",
        "options": ["Routers, switches, and repeaters", "Only keyboards and monitors", "Only application software", "Only fiber optic cables"],
        "correct": 0,
        "explanation": "Network infrastructure devices manage and direct message flow.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Images in digital form are fundamentally represented as:",
        "options": ["Bit patterns, often as pixel matrices", "Continuous analog sine waves only", "ASCII character streams exclusively", "UDP datagram headers"],
        "correct": 0,
        "explanation": "Images encode as bits, commonly pixel grids.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Video may be produced as continuous capture or as:",
        "options": ["Discrete frames arranged to convey motion", "Only simplex infrared signals", "Only hub-broadcast frames", "Unidirectional MAC floods"],
        "correct": 0,
        "explanation": "Video can be continuous or discrete frame sequences suggesting motion.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A passive hub cannot extend distance between nodes because it:",
        "options": ["Does not clean or boost signals before relaying", "Operates at Layer 7", "Maintains a MAC address table", "Performs IP routing"],
        "correct": 0,
        "explanation": "Passive hubs lack amplification; they cannot extend range like active hubs.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Switch segmentation of a LAN improves security by:",
        "options": ["Limiting scope of traffic to relevant segments/recipients", "Encrypting all Layer 7 payloads automatically", "Replacing protocols with OSI standards", "Eliminating the need for protocols"],
        "correct": 0,
        "explanation": "Segmentation confines broadcast domains and directs traffic, reducing exposure.",
    },
    {
        "lecture": "Lecture 1",
        "question": "The pathway quality between sender and recipient is classified as:",
        "options": ["An external communication quality factor", "An internal message property", "A de jure standard", "A TCP/IP layer"],
        "correct": 0,
        "explanation": "Pathway quality is external to message content.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Time allotted for successful communication is considered:",
        "options": ["An external factor affecting quality", "A NIC hardware address", "A presentation layer function", "A mesh topology requirement"],
        "correct": 0,
        "explanation": "Allotted time is an external constraint on communication success.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Text representation in data communications uses:",
        "options": ["Bit patterns, often with codes like ASCII", "Direct analog frequency modulation only", "Only MAC layer headers", "Uncompressed video frames"],
        "correct": 0,
        "explanation": "Text encodes as bit sequences using character codes.",
    },
    {
        "lecture": "Lecture 1",
        "question": "A repeater receives a weak signal and:",
        "options": ["Retransmits it at higher power on another segment", "Filters by IP subnet", "Translates HTTP to FTP", "Assigns logical topologies"],
        "correct": 0,
        "explanation": "Repeaters amplify/regenerate physical signals to extend reach.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Hub inefficiency stems mainly from:",
        "options": ["Flooding all ports and lacking optimal path selection", "Operating above session layer", "Mandatory fiber-only media", "IPv6-only addressing"],
        "correct": 0,
        "explanation": "Hubs broadcast to all devices, wasting bandwidth and causing collisions.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Bridge use for security prevents:",
        "options": ["Traffic from one segment reaching other segments when segmented", "All physical layer noise", "Need for any receivers", "Use of any protocols"],
        "correct": 0,
        "explanation": "Segmentation isolates traffic for security and performance.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Gateway connectivity between organizations with different security policies enables:",
        "options": ["Controlled inter-network communication", "Pure Layer 1 signal boost only", "Elimination of all protocol rules", "Mandatory bus topology"],
        "correct": 0,
        "explanation": "Gateways bridge heterogeneous networks with policy and protocol control.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which characteristic pair distinguishes jitter from general timeliness?",
        "options": ["Jitter is arrival-time variation; timeliness is overall prompt delivery", "Jitter is bit error rate; timeliness is encryption", "Jitter is bandwidth; timeliness is cable type", "They are identical terms"],
        "correct": 0,
        "explanation": "Timeliness concerns delay; jitter concerns inconsistency of delays.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Receiver in a data communication system can be a:",
        "options": ["Computer, workstation, telephone handset, or television", "Protocol specification document only", "Transmission medium cable", "ISO standard exclusively"],
        "correct": 0,
        "explanation": "Receivers are devices that accept messages, including phones and TVs.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Sender devices cited include computers, workstations, and:",
        "options": ["Video cameras and telephone handsets", "Only passive hubs", "Only repeaters", "Only gateways exclusively"],
        "correct": 0,
        "explanation": "Senders encompass various input/capture devices per lecture.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Protocol analogy: French speaker vs Japanese speaker illustrates lack of:",
        "options": ["Agreed communication rules despite physical connection", "Electric power", "Fiber optic cable", "Star topology"],
        "correct": 0,
        "explanation": "Without shared protocol (language rules), communication fails.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Network adapter is another name for:",
        "options": ["Network Interface Card (NIC)", "Router", "Gateway", "Repeater"],
        "correct": 0,
        "explanation": "NIC is also called network adapter or network card.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Switches reduce congestion compared to hubs by:",
        "options": ["Sending frames only to intended recipients using MAC learning", "Broadcasting to every port always", "Operating only at Layer 7", "Ignoring data link addresses"],
        "correct": 0,
        "explanation": "Switches selectively forward, unlike hub flood behavior.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Intended device-only reception defines which characteristic?",
        "options": ["Delivery", "Jitter", "Bandwidth", "Topology type"],
        "correct": 0,
        "explanation": "Delivery requires correct destination device/user only.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Altered but timely data fails primarily which characteristic?",
        "options": ["Accuracy", "Delivery if destination correct", "Network classification", "Duplex mode definition"],
        "correct": 0,
        "explanation": "Uncorrected alteration makes data unusable, violating accuracy.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Which is an example of transmission medium?",
        "options": ["Twisted pair cable carrying signals between sender and receiver", "Application layer HTTP", "MAC address table", "Client-server architecture"],
        "correct": 0,
        "explanation": "Transmission medium is the physical/logical path for message travel.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Router placement is commonly associated with:",
        "options": ["WANs and the Internet connecting different networks", "PAN Bluetooth headphone links only", "Simplex keyboard LED only", "Infrared remote one-way only"],
        "correct": 0,
        "explanation": "Routers interconnect networks, especially WAN/Internet scenarios.",
    },
    {
        "lecture": "Lecture 1",
        "question": "Quality of communication encompasses accuracy, reliability, and:",
        "options": ["Efficiency of transmission and reception", "Only cable color coding", "Only GUI design", "Only printer sharing"],
        "correct": 0,
        "explanation": "Lecture defines quality as accuracy, reliability, and efficiency.",
    },
    {
        "lecture": "Lecture 2",
        "question": "A network spanning a single building under one administration is best classified as:",
        "options": ["LAN", "WAN", "PAN", "Global Internet only"],
        "correct": 0,
        "explanation": "LAN covers a building/campus under single administrative control.",
    },
    {
        "lecture": "Lecture 2",
        "question": "PAN connectivity range is approximately:",
        "options": ["Up to 10 meters", "Up to 100 kilometers", "Cross-continental", "Unlimited with no spatial limit"],
        "correct": 0,
        "explanation": "PAN is personal, typically Bluetooth/infrared within ~10 meters.",
    },
    {
        "lecture": "Lecture 2",
        "question": "MAN typically sits functionally between:",
        "options": ["LAN and WAN", "PAN and simplex only", "Only two PCs point-to-point", "Application and presentation layers only"],
        "correct": 0,
        "explanation": "MAN covers a city, linking LANs toward WAN/Internet uplinks.",
    },
    {
        "lecture": "Lecture 2",
        "question": "The largest WAN cited in the lecture is:",
        "options": ["The Internet", "A single Ethernet bus", "A Bluetooth PAN", "A classroom LAN only"],
        "correct": 0,
        "explanation": "Internet is described as largest WAN covering geographical world.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Mesh topology connectivity means:",
        "options": ["Every device connects to every other device", "All devices share one linear cable", "One central hub links all", "Devices connect only to left/right peers"],
        "correct": 0,
        "explanation": "Mesh provides dedicated links between each pair for redundancy.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Bus topology sends data by:",
        "options": ["Broadcast on shared backbone; devices inspect intended recipient", "Token passing in a ring only", "Central hub forwarding only", "Gateway protocol translation"],
        "correct": 0,
        "explanation": "Bus broadcasts on shared medium; nodes filter by destination.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Star topology central device failure affecting one link:",
        "options": ["Does not necessarily disable entire network unlike single bus break", "Always crashes all nodes", "Forces mesh conversion", "Eliminates need for switches"],
        "correct": 0,
        "explanation": "Star isolates link failures; other nodes remain connected to hub/switch.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Ring topology allows how many simultaneous transmitters per the lecture?",
        "options": ["One device at a time", "Unlimited simultaneous", "Exactly two always", "Zero without gateway"],
        "correct": 0,
        "explanation": "Ring uses token-like single transmission to avoid collisions.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Hybrid topology arises when:",
        "options": ["Multiple connectivity patterns combine arbitrarily", "Only bus is used", "Only PAN exists", "No physical medium is present"],
        "correct": 0,
        "explanation": "Hybrid mixes mesh, bus, star, ring approaches.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Physical topology refers to:",
        "options": ["Physical design: devices, locations, and cable installation", "How data logically transfers regardless of layout", "Only application protocols", "Only IP routing tables"],
        "correct": 0,
        "explanation": "Physical topology is tangible layout; logical is data flow pattern.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Logical topology describes:",
        "options": ["How data transfers in the network versus physical design", "Cable color standards only", "Manufacturer warranty terms", "De jure ISO voting procedures"],
        "correct": 0,
        "explanation": "Logical topology concerns data flow behavior, not cable paths.",
    },
    {
        "lecture": "Lecture 2",
        "question": "P2P architecture lacks:",
        "options": ["A centralized server controlling all node communication", "Any node communication ability", "Physical transmission media", "Protocols entirely"],
        "correct": 0,
        "explanation": "P2P nodes act as both client and server without central control.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Client-server architecture advantage emphasized includes:",
        "options": ["Centralized control and enhanced security", "Zero implementation cost", "No need for servers", "Elimination of all protocols"],
        "correct": 0,
        "explanation": "Client-server offers centralized management and security at scale.",
    },
    {
        "lecture": "Lecture 2",
        "question": "P2P disadvantage noted includes:",
        "options": ["Difficulty managing and securing large numbers of nodes", "Mandatory fiber optic media", "Inability to share files", "Fixed simplex-only flow"],
        "correct": 0,
        "explanation": "Decentralized P2P complicates management and security at scale.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Digital signals differ from analog because digital signals are:",
        "options": ["Discrete binary values less susceptible to noise over distance", "Continuous amplitude/frequency variations", "Always sound waves only", "Unable to represent Ethernet"],
        "correct": 0,
        "explanation": "Digital uses 0/1 bits; less noise susceptibility and degradation over distance.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Analog signals are especially susceptible to:",
        "options": ["Noise and interference causing distortion and degradation", "Only impulse noise on digital exclusively", "MAC address collisions", "Session layer timeout only"],
        "correct": 0,
        "explanation": "Continuous analog signals distort easily from noise/interference.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Thermal noise originates from:",
        "options": ["Heat agitating electronic conductors in the medium", "Lightning impulse only", "Hub broadcasting", "IP routing loops"],
        "correct": 0,
        "explanation": "Thermal noise is unavoidable heat-induced electron agitation up to a level.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Intermodulation noise occurs when:",
        "options": ["Multiple frequencies share a medium and interfere, producing unexpected frequencies", "Single frequency travels perfectly", "Only digital impulses strike", "Ring topology breaks"],
        "correct": 0,
        "explanation": "Shared medium frequency interference creates intermodulation products.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Crosstalk is defined as:",
        "options": ["Foreign signal in one medium affecting signal in another medium", "Thermal heat noise only", "De jure standard conflict", "WAN latency alone"],
        "correct": 0,
        "explanation": "Crosstalk is cross-medium signal leakage.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Impulse noise examples include lightning, short circuits, and:",
        "options": ["Faulty components; digital data is mostly affected", "Steady thermal equilibrium only", "Normal TCP acknowledgments", "Scheduled backups"],
        "correct": 0,
        "explanation": "Impulse noise from irregular disturbances disproportionately hits digital data.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Simplex communication example alignment:",
        "options": ["Keyboard to computer (one direction only)", "Full-duplex telephone conversation", "Half-duplex walkie-talkie press-to-talk", "Bidirectional simultaneous modem default full duplex"],
        "correct": 0,
        "explanation": "Simplex is unidirectional: keyboard input exemplifies transmit-only from keyboard perspective.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Half-duplex allows:",
        "options": ["Both directions but only one direction at a time", "One direction only ever", "Both directions simultaneously always", "No direction without gateway"],
        "correct": 0,
        "explanation": "Half-duplex alternates direction; not simultaneous like full duplex.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Full-duplex is analogous to:",
        "options": ["Two-way street with simultaneous traffic both directions", "One-way street only", "Dead-end road", "Simplex satellite downlink only"],
        "correct": 0,
        "explanation": "Lecture compares full duplex to two-way simultaneous traffic flow.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Network performance may be measured by transmit time and:",
        "options": ["Response time", "MAC bit length only", "Cable jacket color", "Hub port count squared"],
        "correct": 0,
        "explanation": "Performance metrics include transmit time and response time (inquiry to reply).",
    },
    {
        "lecture": "Lecture 2",
        "question": "Network reliability includes frequency of failure, recovery time, and:",
        "options": ["Robustness in catastrophe", "Only GUI responsiveness", "Presentation layer encoding", "PAN range meters"],
        "correct": 0,
        "explanation": "Reliability covers failure rate, recovery, and disaster robustness.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Network security involves policies to prevent unauthorized access, misuse, modification, and:",
        "options": ["Denial of network-accessible resources", "Mandatory bus topology", "Elimination of latency", "Analog-only signaling"],
        "correct": 0,
        "explanation": "Security includes preventing denial of access to network resources.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Point-to-point connection establishes:",
        "options": ["Dedicated channel directly between two devices without intermediary switching for that link", "Shared medium among all devices always", "Application layer translation", "Multipoint Wi-Fi only"],
        "correct": 0,
        "explanation": "Point-to-point is direct dedicated link between two endpoints.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Multipoint connection shares:",
        "options": ["One transmission medium among multiple devices", "Separate dedicated pairwise fiber for every pair always", "Only Layer 7 gateways", "Simplex-only keyboard links exclusively"],
        "correct": 0,
        "explanation": "Multipoint uses shared channel; e.g., wireless AP or bus topology.",
    },
    {
        "lecture": "Lecture 2",
        "question": "De facto standards are characterized by:",
        "options": ["Widespread adoption without official ratification (e.g., TCP/IP, Windows)", "Legislation by accredited bodies only", "Mandatory ISO 1984 vote only", "Never used in industry"],
        "correct": 0,
        "explanation": "De facto emerge from market consensus, not formal standards bodies.",
    },
    {
        "lecture": "Lecture 2",
        "question": "De jure standards are developed by:",
        "options": ["Accredited organizations with formal audited procedures", "Single vendor marketing alone without process", "Random user forums only", "Repeater hardware exclusively"],
        "correct": 0,
        "explanation": "De jure standards come from official standards organizations.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Organizations developing network standards include ISO, IEEE, IETF, ANSI, and:",
        "options": ["CCITT", "Only Bluetooth SIG exclusively as sole body", "Only PC manufacturers internally", "No international bodies"],
        "correct": 0,
        "explanation": "Lecture lists ISO, IEEE, IETF, ANSI, and CCITT.",
    },
    {
        "lecture": "Lecture 2",
        "question": "TCP/IP as a standard example is:",
        "options": ["De facto", "De jure exclusively by ISO OSI replacement", "Never adopted", "Only physical layer coax standard"],
        "correct": 0,
        "explanation": "TCP/IP gained dominance through widespread use—de facto.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Private network definition from administration view:",
        "options": ["Autonomous system inaccessible outside its physical/logical domain", "Any Internet-connected host", "Mandatory mesh WAN", "Public Wi-Fi hotspot"],
        "correct": 0,
        "explanation": "Private networks belong to one organization and block outside access.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Geographic classification from table to worldwide coverage maps to:",
        "options": ["PAN → LAN → MAN → WAN progression of span", "Only OSI seven layers", "Only simplex modes", "Only fiber categories"],
        "correct": 0,
        "explanation": "Span increases: PAN (meters), LAN (building), MAN (city), WAN (wide/global).",
    },
    {
        "lecture": "Lecture 2",
        "question": "Linear structure with left/right peer links describes:",
        "options": ["Ring-like linear peer connection pattern in interconnectivity classification", "Full mesh", "Star hub only", "Gateway translation"],
        "correct": 0,
        "explanation": "Each device connects to left and right peers forming linear/ring structure.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Computer network definition emphasizes:",
        "options": ["Connected devices sharing communication and resources via hardware/software", "Isolated single PC only", "Only analog radio without protocols", "Only printer drivers"],
        "correct": 0,
        "explanation": "Networks connect devices for communication, resource sharing, protocols.",
    },
    {
        "lecture": "Lecture 2",
        "question": "LAN may connect as few as two systems up to:",
        "options": ["16 million systems (per lecture figure)", "Exactly 10 devices maximum", "Two devices only", "Unlimited with no cited bound"],
        "correct": 0,
        "explanation": "Lecture states LAN systems may vary from 2 to as many as 16 million.",
    },
    {
        "lecture": "Lecture 2",
        "question": "MAN backbone commonly uses:",
        "options": ["High-capacity high-speed fibre optics", "Only infrared remotes", "Only UTP Cat3 telephone", "Simplex keyboard cables"],
        "correct": 0,
        "explanation": "MAN relies on high-capacity fiber backbones per lecture.",
    },
    {
        "lecture": "Lecture 2",
        "question": "WAN equipment is described as:",
        "options": ["Very expensive due to high-speed backbone needs", "Cheaper than PAN Bluetooth", "Unnecessary for Internet", "Identical cost to UTP patch cords"],
        "correct": 0,
        "explanation": "WANs use costly equipment for wide-area high-speed connectivity.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Ring topology failure of one device or cable cut can:",
        "options": ["Disrupt entire network", "Never affect others", "Only affect application layer", "Automatically convert to mesh"],
        "correct": 0,
        "explanation": "Ring single break can halt whole loop operation.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Mesh topology drawback emphasized is:",
        "options": ["High cabling and equipment cost", "No redundancy paths", "Mandatory simplex", "Inability to tolerate any failure"],
        "correct": 0,
        "explanation": "Full mesh is expensive despite redundancy benefits.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Data must be converted to electromagnetic signals before sending over:",
        "options": ["Physical medium", "Only application presentations", "Only de jure documents", "MAC address tables alone"],
        "correct": 0,
        "explanation": "Physical transmission requires electromagnetic signal conversion.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Examples of digital signals in lecture include Ethernet, USB, and:",
        "options": ["HDMI", "Analog radio waves only", "Sound waves unencoded", "Hub flood broadcasts as analog only"],
        "correct": 0,
        "explanation": "Ethernet, USB, HDMI are digital signal examples cited.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Examples of analog signals include sound waves and:",
        "options": ["Radio waves (continuous variation)", "Binary Ethernet frames", "ASCII bit patterns", "Discrete pixel grids"],
        "correct": 0,
        "explanation": "Sound and radio waves exemplify continuous analog signals.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Wireless computer networks may use wired or wireless media to connect computers for:",
        "options": ["Information and resource sharing", "Only OSI documentation storage", "Eliminating receivers", "Avoiding all protocols"],
        "correct": 0,
        "explanation": "Networks enable sharing regardless of wired/wireless attachment.",
    },
    {
        "lecture": "Lecture 2",
        "question": "E-commerce application of networks enabled:",
        "options": ["Online product/service sales and new markets", "Only simplex keyboard input", "Elimination of WANs", "Mandatory ring topology"],
        "correct": 0,
        "explanation": "Networks underpin e-commerce growth and market expansion.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Telemedicine benefit cited is:",
        "options": ["Remote medical consultation improving healthcare access", "Physical layer repeater sale", "Hub broadcast efficiency", "MAC address shortening"],
        "correct": 0,
        "explanation": "Telemedicine uses networks for remote care, especially rural access.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Response time differs from transmit time because response time measures:",
        "options": ["Elapsed time between inquiry and response", "One-way propagation delay only", "Cable attenuation rate", "Fiber core diameter"],
        "correct": 0,
        "explanation": "Response time is round-trip service delay; transmit time is one-way message travel.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Bus topology failure of backbone cable can:",
        "options": ["Disable entire network segment", "Improve security automatically", "Force Layer 7 translation", "Increase PAN range"],
        "correct": 0,
        "explanation": "Shared backbone failure isolates all bus-attached devices.",
    },
    {
        "lecture": "Lecture 2",
        "question": "Star topology uses central hub/switch to:",
        "options": ["Forward traffic and reduce collisions versus bus", "Amplify only Layer 7 payloads", "Eliminate all cables", "Mandate WAN routing"],
        "correct": 0,
        "explanation": "Central device manages traffic flow in star topology.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Guided transmission media are characterized by:",
        "options": ["Physical cables providing a fixed propagation path for signals", "Antenna-only air transmission without path", "Application layer protocol bundles", "MAC tables stored in switches"],
        "correct": 0,
        "explanation": "Guided media use twisted pair, coax, fiber with defined physical paths.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Unguided media transmit through:",
        "options": ["Air, vacuum, or water using antennas", "Only copper twisted pairs", "Only fiber optic cores", "Only coaxial shields"],
        "correct": 0,
        "explanation": "Unguided/wireless uses electromagnetic radiation without physical guide.",
    },
    {
        "lecture": "Lecture 3",
        "question": "UTP stands for:",
        "options": ["Unshielded Twisted Pair", "Universal Transmission Protocol", "Unified Transport Packet", "Unregulated Thermal Pathway"],
        "correct": 0,
        "explanation": "UTP is Unshielded Twisted Pair—common in LANs/Ethernet.",
    },
    {
        "lecture": "Lecture 3",
        "question": "STP provides over UTP:",
        "options": ["Better protection from electromagnetic interference via shielding", "Lower cost and easier long-distance reach than fiber", "Immunity to all noise types including impulse", "Application layer encryption by default"],
        "correct": 0,
        "explanation": "STP adds shielding beyond twisting for interference protection.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Twisted pair reduces interference primarily by:",
        "options": ["Pair twisting canceling crosstalk between wires", "Using light pulses instead of electricity", "Operating only at microwave frequencies", "Eliminating the need for repeaters always"],
        "correct": 0,
        "explanation": "Twisting pairs helps cancel electromagnetic interference and crosstalk.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Coaxial cable structure includes:",
        "options": ["Central conductor, insulation, metallic shield, and outer cover", "Only glass core and cladding", "Only single unshielded wire", "Only infrared LED transmitters"],
        "correct": 0,
        "explanation": "Coax has inner conductor, dielectric, shield, and jacket.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Coaxial is used in lecture for:",
        "options": ["Cable TV and broadband internet", "Only PAN Bluetooth headsets", "Only OSI session management", "Only gateway protocol translation"],
        "correct": 0,
        "explanation": "Coax serves cable TV and broadband per transmission media lecture.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Fiber optic transmits data using:",
        "options": ["Light pulses through glass or plastic fibers", "Electrical voltage on copper pairs only", "Sound waves in air ducts", "Hub broadcast electrical floods"],
        "correct": 0,
        "explanation": "Fiber uses light pulses, enabling high speed and EMI immunity.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Single-mode fiber differs from multi-mode because single-mode:",
        "options": ["Allows one straight light path for longer distance and less dispersion", "Has larger core causing multiple paths and shorter reach", "Uses radio waves instead of light", "Is always cheaper to install than UTP"],
        "correct": 0,
        "explanation": "Single-mode: one path, lower loss, longer distance; multi-mode: multiple paths, dispersion limits distance.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Multi-mode fiber limitation emphasized is:",
        "options": ["Dispersion from multiple light paths limiting distance", "Complete immunity to all latency", "Inability to carry any digital data", "Mandatory use only in PAN"],
        "correct": 0,
        "explanation": "Multiple modes cause dispersion, restricting distance compared to single-mode.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Fiber optic advantage over copper includes:",
        "options": ["Immunity to electromagnetic interference", "Lowest installation cost always", "Best mobility for roaming users", "Passes through all walls like radio"],
        "correct": 0,
        "explanation": "Fiber is immune to EMI and offers high bandwidth/security.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Fiber optic disadvantage cited:",
        "options": ["High initial cost and skilled installation required", "Extreme susceptibility to crosstalk", "Maximum range under 10 meters always", "Inability to support ISP backbones"],
        "correct": 0,
        "explanation": "Fiber costs more and needs skilled installers despite performance benefits.",
    },
    {
        "lecture": "Lecture 3",
        "question": "For high electrical interference environments (factories, mining), lecture recommends:",
        "options": ["Fiber optic", "Unshielded twisted pair only", "Infrared remote controls", "Passive hubs exclusively"],
        "correct": 0,
        "explanation": "Fiber avoids EMI; ideal for interference-heavy industrial sites.",
    },
    {
        "lecture": "Lecture 3",
        "question": "High data traffic such as video streaming and cloud systems should prefer:",
        "options": ["Fiber optic", "Infrared remote links", "Unshielded telephone wire only", "Simplex keyboard cables"],
        "correct": 0,
        "explanation": "High bandwidth needs point to fiber for speed/capacity.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Normal office or school networking often uses:",
        "options": ["Twisted pair (UTP)", "Satellite-only uplinks", "Multi-mode fiber to every desk exclusively", "Microwave point-to-point only"],
        "correct": 0,
        "explanation": "UTP is affordable and adequate for typical office/school LAN needs.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Short distances within a building favor:",
        "options": ["UTP or Wi-Fi", "Satellite communication primarily", "WAN leased lines exclusively", "Only multi-mode across continents"],
        "correct": 0,
        "explanation": "Inside buildings, UTP wired or Wi-Fi wireless suit short spans.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Long distances across campus, city, or country favor:",
        "options": ["Fiber optic or microwave", "Infrared remote controls", "UTP Cat3 without repeaters", "PAN Bluetooth only"],
        "correct": 0,
        "explanation": "Long spans need fiber backbones or microwave links.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Low budget installations typically choose:",
        "options": ["Twisted pair cables", "Dedicated satellite networks", "Full mesh fiber to every node", "Microwave towers exclusively"],
        "correct": 0,
        "explanation": "Copper twisted pair is lowest cost wired option cited.",
    },
    {
        "lecture": "Lecture 3",
        "question": "High security requirement environments prefer:",
        "options": ["Fiber optic (harder to tap)", "Open Wi-Fi without encryption", "Hub-based shared collision domains", "Unshielded copper in public areas"],
        "correct": 0,
        "explanation": "Fiber is harder to tap; wired preferred over wireless for security.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Mobility needs for phones and laptops favor:",
        "options": ["Wireless media (radio/Wi-Fi)", "Fixed UTP to each seat only", "Coaxial TV distribution only", "Simplex fiber downlinks only"],
        "correct": 0,
        "explanation": "Wireless supports user movement; wired suits fixed workstations.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Attenuation refers to:",
        "options": ["Loss of signal strength as distance increases", "Increase of bandwidth with cable length", "Protocol header encapsulation", "MAC address duplication"],
        "correct": 0,
        "explanation": "Attenuation is signal weakening over distance; lower is better for long links.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Media with lowest attenuation for long distance per lecture:",
        "options": ["Fiber optic", "Unshielded twisted pair", "Infrared LED", "Bluetooth PAN"],
        "correct": 0,
        "explanation": "Fiber covers longest distance with lower attenuation than copper.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Wired media are generally __ compared to wireless for tapping/interception:",
        "options": ["More secure (harder to intercept)", "Less secure always", "Identical in all environments", "Unrelated to security policy"],
        "correct": 0,
        "explanation": "Wired generally more secure; wireless more exposed to interception.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Wireless installation advantage:",
        "options": ["Easier deployment where cabling is impractical", "Always highest bandwidth vs fiber", "Zero interference vulnerability", "Longest range without line-of-sight"],
        "correct": 0,
        "explanation": "Wireless eases install in open or hard-to-cable areas.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Radio waves frequency range cited (~3 kHz–1 GHz) are used in:",
        "options": ["Wi-Fi, Bluetooth, and radio broadcasting", "Only fiber optic cores", "Only coaxial center conductors", "Only TCP transport layer"],
        "correct": 0,
        "explanation": "Radio waves support Wi-Fi, Bluetooth, broadcasting per lecture.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Radio waves can:",
        "options": ["Pass through walls and buildings", "Require strict line-of-sight always", "Never suffer interference", "Only travel in fiber cores"],
        "correct": 0,
        "explanation": "Radio penetrates obstacles better than higher-frequency microwave/IR in many cases.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Microwave frequency range cited is approximately:",
        "options": ["1 GHz to 300 GHz", "3 Hz to 3 kHz", "400 THz to 500 THz", "Only 2.4 kHz exactly"],
        "correct": 0,
        "explanation": "Microwaves span ~1 GHz–300 GHz for satellite and point-to-point links.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Microwave links require:",
        "options": ["Line-of-sight between antennas", "No alignment or planning", "Only underground fiber ducts", "Only hub broadcast topology"],
        "correct": 0,
        "explanation": "Microwave needs clear line-of-sight for point-to-point communication.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Microwave disadvantage includes:",
        "options": ["Weather effects such as rain fade", "Complete inability to carry data", "Mandatory use only inside LAN closets", "Zero latency always"],
        "correct": 0,
        "explanation": "Rain fade and weather can degrade microwave signals.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Infrared frequency range cited is approximately:",
        "options": ["300 GHz to 400 THz", "3 kHz to 1 GHz", "1 GHz to 300 GHz", "Only 802.11ax band"],
        "correct": 0,
        "explanation": "Infrared occupies ~300 GHz–400 THz for short-range IR communication.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Infrared cannot:",
        "options": ["Penetrate obstacles; requires line-of-sight", "Be used in remote controls", "Provide short-range links", "Operate in confined spaces securely"],
        "correct": 0,
        "explanation": "IR does not pass through obstacles; needs direct line-of-sight.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Satellite communication disadvantage emphasized:",
        "options": ["High cost and signal latency (delay)", "Inability to cover wide areas", "Requirement for UTP to each user", "Immunity to all weather"],
        "correct": 0,
        "explanation": "Satellites cost more and introduce propagation delay/latency.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Satellite communication advantage:",
        "options": ["Very wide geographic coverage where cables impractical", "Lowest latency for gaming", "Cheapest per-bit cost always", "Best for PAN headphone links"],
        "correct": 0,
        "explanation": "Satellites cover remote/vast areas where cabling is impractical.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Reasons for wireless technology include temporary installations and:",
        "options": ["People who move within or travel outside work environments", "Mandatory elimination of all protocols", "Replacement of all fiber backbones", "Exclusive use in data link layer only"],
        "correct": 0,
        "explanation": "Wireless suits mobility, temporary sites, and impossible/inconvenient cabling.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Choosing media depends on bandwidth, distance, cost, environment, security, reliability, and:",
        "options": ["Mobility and future expansion needs", "Only cable jacket color", "Only OSI layer count", "Only MAC OUI vendor"],
        "correct": 0,
        "explanation": "Selection weighs mobility, growth, interference, and operational factors.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Expecting network growth and higher future data needs suggests:",
        "options": ["Fiber optic investment", "Cat3 telephone wire only", "Infrared remotes exclusively", "Passive hub LANs"],
        "correct": 0,
        "explanation": "Fiber supports future bandwidth expansion per lecture guidance.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Stable indoor environments with low interference often use:",
        "options": ["UTP", "Microwave towers", "Satellite downlinks", "Multi-hop mesh only"],
        "correct": 0,
        "explanation": "UTP suffices in stable indoor low-interference settings.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Interference-prone areas should use:",
        "options": ["Shielded cables or fiber", "Unshielded copper only", "Hub-based bus always", "Open microwave without planning"],
        "correct": 0,
        "explanation": "Shielding or fiber mitigates interference in noisy environments.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Reliability ranking emphasized places __ as most reliable:",
        "options": ["Fiber optic", "Unshielded copper in factories", "Consumer radio only", "Infrared through walls"],
        "correct": 0,
        "explanation": "Fiber transmits consistently with minimal errors—most reliable medium cited.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Copper twisted pair disadvantages include:",
        "options": ["Limited distance/speed and EMI susceptibility", "Complete immunity to noise", "Longest global reach without regeneration", "Higher cost than satellite always"],
        "correct": 0,
        "explanation": "UTP is cheap but distance/speed limited and EMI-sensitive.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Coax advantages over twisted pair include:",
        "options": ["Higher bandwidth and less noise/interference", "Lowest cost and easiest fiber replacement", "Immunity to all attenuation", "Use only in PAN 10 m range"],
        "correct": 0,
        "explanation": "Coax offers better shielding and bandwidth than basic twisted pair.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Coax disadvantages include:",
        "options": ["More expensive, bulkier, harder to install than twisted pair", "Lower bandwidth than UTP always", "Inability to carry broadband", "Mandatory Layer 7 operation"],
        "correct": 0,
        "explanation": "Coax is costlier and harder to install despite performance gains.",
    },
    {
        "lecture": "Lecture 3",
        "question": "UTP categories classify cables by:",
        "options": ["Performance, speed, and bandwidth capability", "Only outer jacket color", "Only manufacturer country", "OSI layer number"],
        "correct": 0,
        "explanation": "UTP categories (Cat5e, Cat6, etc.) rate performance and bandwidth.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Open or hard-to-cable areas should consider:",
        "options": ["Wireless (radio/microwave)", "Trenching fiber to every desk only", "Bus topology coax only", "Simplex keyboard wiring"],
        "correct": 0,
        "explanation": "Wireless fits areas where physical cabling is difficult.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Public access environments prefer wired over wireless primarily for:",
        "options": ["Better security control vs open wireless exposure", "Lower bandwidth always", "Elimination of all NICs", "Mandatory half-duplex"],
        "correct": 0,
        "explanation": "Wired preferred in public settings due to wireless security concerns.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Transmission speed in media characteristics depends on:",
        "options": ["Type of media used", "Only application layer protocol names", "Only star topology choice", "Only de jure standard votes"],
        "correct": 0,
        "explanation": "Actual data rate varies by medium type and implementation.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Noise and interference affect copper more than:",
        "options": ["Fiber optic (minimal interference in glass light path)", "Microwave only in vacuum", "Satellite only in LAN closet", "UTP in shielded vault only"],
        "correct": 0,
        "explanation": "Fiber has minimal noise/interference vs copper cables.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Flexibility and mobility are highest for:",
        "options": ["Wireless media", "Fixed UTP desktop wiring", "Underground fiber only", "Coaxial cable TV drops only"],
        "correct": 0,
        "explanation": "Wireless enables device movement; wired is fixed workstation oriented.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Fixed workstations without mobility needs should use:",
        "options": ["Wired connections (typically twisted pair or fiber)", "Satellite dishes at each desk", "Infrared across buildings", "Only multipoint bus without medium"],
        "correct": 0,
        "explanation": "Fixed users benefit from reliable wired links.",
    },
    {
        "lecture": "Lecture 3",
        "question": "Small stable networks with modest needs may remain on:",
        "options": ["Twisted pair infrastructure", "Global satellite backbone exclusively", "Microwave city rings only", "Multi-mode transcontinental fiber mandatory"],
        "correct": 0,
        "explanation": "Small stable networks can stay on cost-effective twisted pair.",
    },
    {
        "lecture": "Lecture 4",
        "question": "The OSI model has how many layers?",
        "options": ["7", "4", "5", "3"],
        "correct": 0,
        "explanation": "OSI is a seven-layer reference model for network communication.",
    },
    {
        "lecture": "Lecture 4",
        "question": "The TCP/IP model has how many layers?",
        "options": ["4", "7", "5", "2"],
        "correct": 0,
        "explanation": "TCP/IP uses four layers: link, internet, transport, application.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 7 is the:",
        "options": ["Application layer", "Physical layer", "Network layer", "Data link layer"],
        "correct": 0,
        "explanation": "Layer 7 Application provides network services to user applications.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 1 is the:",
        "options": ["Physical layer", "Transport layer", "Session layer", "Presentation layer"],
        "correct": 0,
        "explanation": "Layer 1 Physical handles bit transmission over physical medium.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 3 is the:",
        "options": ["Network layer", "Data link layer", "Application layer", "Physical layer"],
        "correct": 0,
        "explanation": "Layer 3 Network handles routing and logical addressing.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 2 is the:",
        "options": ["Data link layer", "Transport layer", "Session layer", "Network layer"],
        "correct": 0,
        "explanation": "Layer 2 Data Link handles framing and MAC addressing.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 4 is the:",
        "options": ["Transport layer", "Presentation layer", "Physical layer", "Application layer"],
        "correct": 0,
        "explanation": "Layer 4 Transport ensures end-to-end delivery (TCP/UDP).",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 5 is the:",
        "options": ["Session layer", "Network layer", "Data link layer", "Physical layer"],
        "correct": 0,
        "explanation": "Layer 5 Session manages dialog control and synchronization.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI Layer 6 is the:",
        "options": ["Presentation layer", "Transport layer", "Network layer", "Session layer"],
        "correct": 0,
        "explanation": "Layer 6 Presentation handles translation, encryption, compression.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP Application layer corresponds to OSI layers:",
        "options": ["5, 6, and 7 (Session, Presentation, Application)", "1 and 2 only", "3 and 4 only", "Only layer 4"],
        "correct": 0,
        "explanation": "TCP/IP application layer maps to OSI top three layers.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP Network Interface layer corresponds to OSI:",
        "options": ["Layers 1 and 2 (Physical and Data Link)", "Layers 3 and 4", "Layers 5–7", "Layer 3 only"],
        "correct": 0,
        "explanation": "TCP/IP link/interface combines OSI physical and data link.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP Internet layer corresponds primarily to OSI:",
        "options": ["Network layer (Layer 3)", "Application layer", "Session layer", "Physical layer"],
        "correct": 0,
        "explanation": "TCP/IP internet layer aligns with OSI network layer routing/addressing.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP Transport layer aligns with OSI:",
        "options": ["Transport layer (Layer 4)", "Presentation layer", "Data link layer", "Physical layer"],
        "correct": 0,
        "explanation": "Both models have transport layer for end-to-end communication.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI was developed by:",
        "options": ["ISO (International Organization for Standardization)", "ARPANET exclusively alone", "IEEE only without ISO", "Microsoft exclusively"],
        "correct": 0,
        "explanation": "OSI is an ISO international standard reference model.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP was developed in context of:",
        "options": ["ARPANET / Internet evolution", "ISO 1984 formal vote only", "Bluetooth SIG", "Coaxial TV standards only"],
        "correct": 0,
        "explanation": "TCP/IP emerged from ARPANET research leading to Internet.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI model is classified as a:",
        "options": ["Reference model", "Specific protocol suite implementation only", "Physical cable standard", "MAC address format"],
        "correct": 0,
        "explanation": "OSI is reference framework, not a protocol implementation itself.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP model is classified as a:",
        "options": ["Protocol model (describes TCP/IP suite functions)", "Pure reference without protocols", "Only Layer 1 specification", "Only Ethernet 802.3 document"],
        "correct": 0,
        "explanation": "TCP/IP model maps closely to actual TCP/IP protocol suite.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Reference models primarily aim to:",
        "options": ["Aid understanding of functions/processes without implementation detail", "Replace all vendor hardware", "Specify exact cable pinouts only", "Eliminate need for protocols"],
        "correct": 0,
        "explanation": "Reference models clarify concepts; protocol models match specific suites.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Protocol models provide:",
        "options": ["Structure closely matching a particular protocol suite (e.g., TCP/IP)", "No relation to real protocols", "Only OSI layer naming", "Only physical topology diagrams"],
        "correct": 0,
        "explanation": "Protocol models mirror real protocol stack organization.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Layered architecture benefit: modification in one layer should:",
        "options": ["Not affect other layers due to independence/abstraction", "Require rebuilding entire network hardware", "Eliminate encapsulation", "Merge all layers into one"],
        "correct": 0,
        "explanation": "Layer independence allows changes locally without breaking whole stack.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Encapsulation in OSI means each layer:",
        "options": ["Adds its own header/trailer to data from layer above", "Removes all headers from sender", "Only encrypts physical bits", "Ignores lower layer services"],
        "correct": 0,
        "explanation": "Encapsulation wraps data with layer-specific control information.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI adoption as international standard occurred in:",
        "options": ["1984", "1973 only without adoption", "1990 ARPANET shutdown year only", "2000 exclusively"],
        "correct": 0,
        "explanation": "ISO formally adopted OSI architecture in 1984 per lecture history.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Initial OSI intent in 1983 was:",
        "options": ["Detailed specification of actual interfaces", "Replacement of TCP/IP on January 1 1983", "Elimination of physical layer", "Only textbook publication without standardization"],
        "correct": 0,
        "explanation": "OSI began aiming at detailed interface specs before reference use evolved.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP paper by Cerf and Kahn published in:",
        "options": ["1974", "1984 ISO adoption year", "1990", "1969 ARPANET birth only"],
        "correct": 0,
        "explanation": "1974 paper 'A Protocol for Packet Network Interconnection' described TCP/IP concepts.",
    },
    {
        "lecture": "Lecture 4",
        "question": "ARPANET switched from NCP to TCP/IP on:",
        "options": ["January 1, 1983", "January 1, 1974", "1984 ISO vote day", "1990 shutdown day exclusively"],
        "correct": 0,
        "explanation": "January 1, 1983 marks ARPANET mandatory TCP/IP adoption.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP is described as:",
        "options": ["Connection-oriented with reliability and sequencing", "Connectionless only without ordering", "Physical layer signal booster", "Application layer gateway translator"],
        "correct": 0,
        "explanation": "TCP provides reliable, connection-oriented delivery with ordering and flow control.",
    },
    {
        "lecture": "Lecture 4",
        "question": "IPv4 provided approximately how many addressable devices per lecture?",
        "options": ["4.29 million unique addresses (32-bit)", "4.3 billion devices", "128-bit unlimited flat count", "256 addresses only"],
        "correct": 0,
        "explanation": "IPv4 32-bit space supports roughly 4.29 billion addresses; lecture cites ~4.29 million unique devices in one passage (32-bit address space context).",
    },
    {
        "lecture": "Lecture 4",
        "question": "IPv6 uses:",
        "options": ["128-bit network addresses", "32-bit addresses only", "48-bit MAC as IP", "16-bit addresses"],
        "correct": 0,
        "explanation": "IPv6 expands to 128-bit addressing for vastly more devices.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI follows a __ approach; TCP/IP follows a __ approach per comparison table:",
        "options": ["Vertical; horizontal", "Horizontal; vertical", "Circular; linear", "Mesh; bus"],
        "correct": 0,
        "explanation": "Comparison table states OSI vertical vs TCP/IP horizontal approach.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI transport layer is described as:",
        "options": ["Connection-oriented only", "Both connection-oriented and connectionless", "Connectionless only always", "Physical signal only"],
        "correct": 0,
        "explanation": "OSI model presents transport as connection-oriented; TCP/IP transport includes both TCP and UDP modes.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP transport layer supports:",
        "options": ["Both connection-oriented (TCP) and connectionless (UDP) behavior", "Connection-oriented only with no UDP", "Neither mode; only routing", "Only session synchronization"],
        "correct": 0,
        "explanation": "TCP/IP transport layer encompasses TCP (connection-oriented) and UDP (connectionless).",
    },
    {
        "lecture": "Lecture 4",
        "question": "Session and presentation layers exist in:",
        "options": ["OSI but not in TCP/IP model", "TCP/IP but not OSI", "Neither model", "Ethernet model only"],
        "correct": 0,
        "explanation": "TCP/IP collapses session/presentation into application layer.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI clearly distinguishes:",
        "options": ["Services, interfaces, and protocols", "Only cable types", "Only topology shapes", "Only PAN range"],
        "correct": 0,
        "explanation": "OSI separates services, interfaces, protocols; TCP/IP lacks such crisp distinctions.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Chronology comparison: OSI was defined __ the advent of the Internet per lecture table:",
        "options": ["After", "Before", "Simultaneously with January 1983 only", "Never related temporally"],
        "correct": 0,
        "explanation": "Table notes OSI defined after Internet advent; TCP/IP before/with Internet growth.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Layered tasks aim to divide design into:",
        "options": ["Small pieces with each layer adding services upward", "One monolithic program only", "Physical cables only", "Application GUIs only"],
        "correct": 0,
        "explanation": "Layering splits functionality into manageable modules building services upward.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Modularity in layered architecture enables:",
        "options": ["Independent implementation, testing, and fault isolation per layer", "Mandatory single-vendor hardware", "Elimination of standards", "Removal of all headers"],
        "correct": 0,
        "explanation": "Modularity supports independent layer development and easier debugging.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Standardization benefit of layered architecture:",
        "options": ["Interoperability between diverse devices and protocols", "Proprietary lock-in only", "Elimination of TCP/IP", "Mandatory analog signaling"],
        "correct": 0,
        "explanation": "Standard layers enable heterogeneous interoperability.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Abstraction in layered architecture allows developers to:",
        "options": ["Work on one layer without lower-layer implementation details", "Ignore all protocols entirely", "Merge layers 1–7 into NIC firmware only", "Disable encapsulation"],
        "correct": 0,
        "explanation": "Upper layers use services without knowing lower-layer internals.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Flexibility of layered architecture allows:",
        "options": ["Adding new services at appropriate layer without disrupting others", "No future protocol changes ever", "Only physical layer updates", "Elimination of network layer"],
        "correct": 0,
        "explanation": "New functionality can be inserted at suitable layer as networks evolve.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI disadvantage cited includes:",
        "options": ["Complexity and implementation difficulty in large networks", "Too few layers to model networks", "No encapsulation support", "Lack of international recognition"],
        "correct": 0,
        "explanation": "OSI can be complex with overhead and inconsistent vendor implementations.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI advantage cited includes:",
        "options": ["Improved troubleshooting via layer separation", "Elimination of all security needs", "Guaranteed zero overhead", "Replacement of all physical media"],
        "correct": 0,
        "explanation": "Layer separation aids diagnosing where failures occur.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP advantage cited includes:",
        "options": ["Wide adoption, simplicity relative to OSI, scalability, interoperability", "Zero security vulnerabilities", "No protocol complexity at all", "Seven-layer strict enforcement"],
        "correct": 0,
        "explanation": "TCP/IP is Internet foundation—simple, scalable, widely adopted.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP disadvantage cited includes:",
        "options": ["Security vulnerabilities and complexity with many protocols/standards", "Too few layers to describe Internet", "No scalability ever", "Cannot support IP addressing"],
        "correct": 0,
        "explanation": "TCP/IP faces security threats and complexity as Internet grows.",
    },
    {
        "lecture": "Lecture 4",
        "question": "OSI is NOT a protocol; it is:",
        "options": ["A model for understanding/designing interoperable network architecture", "The Ethernet frame format", "The TCP header specification", "A cable category standard"],
        "correct": 0,
        "explanation": "OSI is conceptual reference model, not executable protocol.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Lower OSI layers (1–3) devices from lecture/chapter context include:",
        "options": ["Repeater/hub (L1), switch/bridge (L2), router (L3)", "Gateway only at all three", "Only application servers", "Only fiber cables without devices"],
        "correct": 0,
        "explanation": "Repeaters/hubs L1; switches/bridges L2; routers L3.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Hierarchical OSI structure means:",
        "options": ["Lower layers provide services to higher layers", "Higher layers transmit raw bits directly on cable", "All layers are peers without ordering", "Only layer 7 communicates with layer 1"],
        "correct": 0,
        "explanation": "OSI hierarchy stacks services upward from physical to application.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Protocol independence in OSI means:",
        "options": ["Model does not mandate specific protocols at each layer", "Only TCP may be used", "Only Ethernet may be used", "Protocols are forbidden"],
        "correct": 0,
        "explanation": "OSI defines framework; various protocols can implement each layer.",
    },
    {
        "lecture": "Lecture 4",
        "question": "TCP/IP internet layer uses predominantly:",
        "options": ["IP (Internet Protocol) for routing and addressing", "MAC addresses only for global routing", "HTTP for packet forwarding", "FTP for subnet masking"],
        "correct": 0,
        "explanation": "IP operates at TCP/IP internet (network) layer for addressing/routing.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Presentation layer responsibilities include:",
        "options": ["Data translation, encryption, and compression", "Physical bit timing on cable", "IP route discovery", "MAC learning on switches"],
        "correct": 0,
        "explanation": "Presentation layer formats/transforms data for application consumption.",
    },
    {
        "lecture": "Lecture 4",
        "question": "Session layer responsibilities include:",
        "options": ["Dialog control and synchronization between applications", "Electrical signal regeneration", "Frame switching by MAC", "Packet routing by IP"],
        "correct": 0,
        "explanation": "Session layer manages sessions—establishment, maintenance, synchronization.",
    },
] + LECTURE5_QUESTIONS


if __name__ == "__main__":
    main()
