"""50 difficult MCQ questions from Lecture 5 – Computer Network Management."""

LECTURE5_QUESTIONS = [
    {
        "lecture": "Lecture 5",
        "question": "Computer Network Management is best defined as the process of:",
        "options": [
            "Monitoring, administering, maintaining, and securing networks for efficient reliable secure operation",
            "Installing cables and terminating RJ-45 connectors only",
            "Writing application software unrelated to infrastructure",
            "Replacing hardware annually regardless of health",
        ],
        "correct": 0,
        "explanation": "Lecture 5 defines network management as monitoring, administering, maintaining, and securing networks using tools, protocols, policies, and procedures.",
    },
    {
        "lecture": "Lecture 5",
        "question": "In the FCAPS model developed by ISO, what does the 'F' represent?",
        "options": ["Fault management", "Firewall management", "Fiber management", "Flow control management"],
        "correct": 0,
        "explanation": "FCAPS: Fault, Configuration, Accounting, Performance, Security. Fault management detects, isolates, and corrects network problems.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Configuration management within FCAPS primarily involves:",
        "options": [
            "Managing device settings and network changes",
            "Counting bytes transferred per user only",
            "Encrypting all emails at rest",
            "Replacing failed power supplies automatically",
        ],
        "correct": 0,
        "explanation": "Configuration management handles device settings and controlled network changes.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Accounting management in FCAPS is concerned with:",
        "options": [
            "Tracking resource usage",
            "Detecting cable breaks",
            "Assigning MAC addresses",
            "Designing website layouts",
        ],
        "correct": 0,
        "explanation": "Accounting management tracks how network resources are consumed.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Performance management under FCAPS focuses on monitoring:",
        "options": ["Speed, traffic, and efficiency", "Employee attendance only", "Software licensing keys", "Printer toner levels exclusively"],
        "correct": 0,
        "explanation": "Performance management monitors speed, traffic patterns, and overall network efficiency.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Security management in FCAPS aims to:",
        "options": [
            "Protect the network from threats and unauthorized access",
            "Maximize raw bandwidth at any security cost",
            "Disable all logging for privacy",
            "Remove firewalls to reduce latency",
        ],
        "correct": 0,
        "explanation": "Security management protects against threats and unauthorized access.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Which FCAPS area would isolate a failing switch port and alert administrators?",
        "options": ["Fault management", "Accounting management", "Configuration management only without detection", "Security management exclusively"],
        "correct": 0,
        "explanation": "Fault management detects, isolates, and corrects network problems including device failures.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Network management devices explicitly listed in Lecture 5 include all EXCEPT:",
        "options": ["Repeaters as the primary management focus", "Routers", "Firewalls", "Wireless access points"],
        "correct": 0,
        "explanation": "Lecture 5 lists routers, switches, servers, firewalls, and wireless APs; repeaters are not emphasized as managed devices here.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Proactive network monitoring primarily helps organizations:",
        "options": [
            "Detect issues before they escalate, reducing repair costs and outage losses",
            "Eliminate the need for any security policies",
            "Avoid all bandwidth monitoring",
            "Remove disaster recovery planning",
        ],
        "correct": 0,
        "explanation": "Proactive monitoring detects problems early, cutting operational costs and productivity losses from outages.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Which enterprise benefit ties configuration backups, disaster recovery, and redundancy planning together?",
        "options": ["Supports business continuity", "Accounting management only", "Reduces cable length", "Eliminates need for firewalls"],
        "correct": 0,
        "explanation": "Business continuity is supported through backups, DR plans, and redundancy so operations continue during failures.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Visibility and control in network management gives administrators real-time insight into all EXCEPT:",
        "options": ["Employee salary grades", "Network health", "Traffic flows", "Security events"],
        "correct": 0,
        "explanation": "Visibility covers network health, device status, traffic flows, and security events—not HR payroll data.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Routers in managed networks primarily:",
        "options": [
            "Connect different networks and direct packets based on IP addresses",
            "Forward frames within a LAN using MAC addresses only",
            "Store user files for shared access",
            "Capture packets for protocol analysis by default",
        ],
        "correct": 0,
        "explanation": "Routers interconnect networks (e.g., LAN to WAN) and route by IP, often supporting routing protocols and filtering.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Managed switches in Lecture 5 are described as forwarding data based on:",
        "options": ["MAC addresses", "IP addresses globally", "URL hostnames", "FTP session IDs"],
        "correct": 0,
        "explanation": "Switches connect LAN devices and forward using MAC addresses; they may support VLANs and port security.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Which switch capabilities are highlighted for network management contexts?",
        "options": ["VLANs, port security, and traffic monitoring", "Satellite uplink modulation only", "DNS registration", "HTML rendering"],
        "correct": 0,
        "explanation": "Switches support VLANs, port security, and traffic monitoring per Lecture 5.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Servers in network management provide shared services such as:",
        "options": ["File storage, email, databases, and web hosting", "Only physical cable testing", "MAC address manufacturing", "Optical fiber splicing"],
        "correct": 0,
        "explanation": "Servers deliver shared services including files, email, databases, and web hosting (Windows Server, Linux, etc.).",
    },
    {
        "lecture": "Lecture 5",
        "question": "Firewalls in a managed network:",
        "options": [
            "Filter incoming/outgoing traffic and enforce security policies",
            "Regenerate signals at the physical layer only",
            "Assign DHCP leases exclusively",
            "Replace routers for all WAN connectivity",
        ],
        "correct": 0,
        "explanation": "Firewalls filter traffic and enforce policies; they may be hardware- or software-based.",
    },
    {
        "lecture": "Lecture 5",
        "question": "A Network Management System (NMS) is best described as:",
        "options": [
            "Software platform for monitoring, managing, and controlling infrastructure centrally",
            "A type of UTP cable category",
            "An OSI layer 1 repeater",
            "A peer-to-peer file sharing protocol",
        ],
        "correct": 0,
        "explanation": "NMS is administrator software providing centralized visibility, fault detection, and control.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Which is NOT listed as a key NMS function in Lecture 5?",
        "options": ["Word processing document editing", "Monitoring devices and traffic", "Fault detection and alerting", "Performance analysis of bandwidth and latency"],
        "correct": 0,
        "explanation": "NMS functions include monitoring, fault detection, configuration management, performance analysis, and security monitoring.",
    },
    {
        "lecture": "Lecture 5",
        "question": "In NMS architecture, agents are:",
        "options": [
            "Software on managed devices that send data to the management server",
            "Physical cables connecting floors",
            "End-user web browsers only",
            "Backup generators for data centers",
        ],
        "correct": 0,
        "explanation": "Agents are installed on managed devices to report data to the NMS management server.",
    },
    {
        "lecture": "Lecture 5",
        "question": "The most common management protocol cited for NMS communication is:",
        "options": ["SNMP", "HTTP only", "FTP exclusively", "SMTP for all device polling"],
        "correct": 0,
        "explanation": "SNMP (Simple Network Management Protocol) is the most common NMS protocol listed.",
    },
    {
        "lecture": "Lecture 5",
        "question": "ICMP in network management is primarily used for:",
        "options": ["Diagnostics", "Traffic flow export analysis", "Configuration backup storage", "Email relay"],
        "correct": 0,
        "explanation": "ICMP supports diagnostic functions such as reachability testing (e.g., ping).",
    },
    {
        "lecture": "Lecture 5",
        "question": "NetFlow in the NMS context is associated with:",
        "options": ["Traffic analysis", "Fault isolation at layer 1 only", "MAC address assignment", "Presentation-layer encryption"],
        "correct": 0,
        "explanation": "NetFlow is listed as a management protocol/tooling area for traffic analysis.",
    },
    {
        "lecture": "Lecture 5",
        "question": "A centralized NMS characteristic that creates operational risk is:",
        "options": ["Single point of failure", "Too many management servers", "Mandatory geographic distribution", "Inability to use a unified dashboard"],
        "correct": 0,
        "explanation": "Centralized NMS uses one server—all devices report to it, creating a single point of failure.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Centralized NMS is best suited for:",
        "options": ["Small to medium organizations", "Large telecom backbone only", "Satellite-only networks without servers", "Networks requiring mandatory multi-server fault tolerance"],
        "correct": 0,
        "explanation": "Centralized NMS advantages include simple setup and lower cost—ideal for small/medium orgs.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Distributed NMS primarily improves:",
        "options": ["Scalability and fault tolerance", "Simplicity for tiny home LANs", "Elimination of all management servers", "Removal of monitoring agents"],
        "correct": 0,
        "explanation": "Distributed NMS uses multiple servers across segments—high scalability, no single point of failure.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Distributed NMS is best for:",
        "options": ["Large enterprises and telecom networks", "Single-room Bluetooth PAN only", "Networks with no segmentation", "Organizations avoiding all management costs"],
        "correct": 0,
        "explanation": "Distributed architecture suits large enterprises and telecom where scale and resilience matter.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Cloud-Based NMS is accessed via:",
        "options": ["Web interface over the internet", "Only serial console cables", "Exclusive infrared line-of-sight", "Manual paper logbooks"],
        "correct": 0,
        "explanation": "Cloud-Based NMS is hosted online and managed remotely through a browser.",
    },
    {
        "lecture": "Lecture 5",
        "question": "A key disadvantage of Cloud-Based NMS noted in Lecture 5 is:",
        "options": ["Dependence on internet connectivity", "Mandatory on-premise server farms", "Inability to scale", "Prohibition of remote access"],
        "correct": 0,
        "explanation": "Cloud NMS depends on internet connectivity and may raise security concerns.",
    },
    {
        "lecture": "Lecture 5",
        "question": "On-Premises NMS offers which advantage over typical cloud deployment?",
        "options": ["Higher data security and full local control", "Zero IT expertise required", "No hardware costs ever", "Automatic immunity from maintenance"],
        "correct": 0,
        "explanation": "On-premises NMS runs on local infrastructure with full control and typically higher data security.",
    },
    {
        "lecture": "Lecture 5",
        "question": "On-Premises NMS disadvantages include:",
        "options": ["Expensive setup/maintenance and need for IT expertise", "No customization possible", "Mandatory cloud-only access", "Inability to secure data locally"],
        "correct": 0,
        "explanation": "On-prem NMS costs more to deploy/maintain and requires skilled IT staff.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Which feature is listed for a good NMS?",
        "options": ["Network mapping and visualization", "Exclusive use of half-duplex links", "Removal of all alerting", "Manual-only configuration with no remote access"],
        "correct": 0,
        "explanation": "Good NMS features include real-time dashboards, alerts, network mapping, reporting, remote config, and scalability.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Using an NMS helps achieve all EXCEPT:",
        "options": ["Guaranteed elimination of all cyber threats forever", "Early problem detection", "Reduced downtime", "Simplified administration"],
        "correct": 0,
        "explanation": "NMS benefits include early detection, less downtime, better performance, security monitoring, and simplified admin—not absolute threat elimination.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Nagios is categorized in Lecture 5 as a:",
        "options": ["Monitoring tool focused on health alerts", "Packet analysis sniffer", "SIEM platform exclusively", "Traffic flow exporter only"],
        "correct": 0,
        "explanation": "Nagios monitors system health and alerts administrators when issues occur.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Zabbix is described as:",
        "options": [
            "A modern all-in-one monitoring solution for real-time monitoring, visualization, and automation",
            "A layer-1 repeater vendor",
            "A coaxial cable standard",
            "An infrared remote protocol",
        ],
        "correct": 0,
        "explanation": "Zabbix provides real-time monitoring, visualization, and automation in one platform.",
    },
    {
        "lecture": "Lecture 5",
        "question": "PRTG Network Monitor specializes in:",
        "options": [
            "Real-time monitoring of network performance, devices, traffic, and applications centrally",
            "Only DNS registration",
            "Fiber optic splicing guides",
            "Desktop word processing",
        ],
        "correct": 0,
        "explanation": "PRTG monitors performance, devices, traffic, and applications in real time via a centralized system.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Wireshark is primarily used for:",
        "options": [
            "Capturing and examining network traffic (packet analysis) in real time",
            "Automating switch VLAN assignments agentlessly",
            "Hosting corporate email databases",
            "Routing IP packets between autonomous systems",
        ],
        "correct": 0,
        "explanation": "Wireshark is a protocol analyzer/packet sniffer for troubleshooting, analysis, and security investigations.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Tcpdump differs from Wireshark mainly because it is:",
        "options": [
            "A command-line packet analyzer widely used on Linux/Unix",
            "A GUI-only Windows monitoring dashboard",
            "A hardware firewall appliance",
            "A cloud NMS with no capture ability",
        ],
        "correct": 0,
        "explanation": "Tcpdump is a powerful CLI packet analyzer for Linux/Unix troubleshooting and security monitoring.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Deep packet inspection and protocol analysis are functions of:",
        "options": ["Packet analysis tools", "Monitoring tools like Nagios only", "Configuration tools like Ansible only", "Performance tools like NetFlow Analyzer exclusively without capture"],
        "correct": 0,
        "explanation": "Packet analysis tools (Wireshark, Tcpdump) perform DPI, protocol analysis, and anomaly identification.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Ansible is characterized in Lecture 5 as:",
        "options": [
            "An agentless automation tool using human-readable scripts for configuration and orchestration",
            "A model-driven tool requiring agents on every device like Puppet",
            "An IDS/IPS for inline blocking only",
            "A flow-based analyzer using NetFlow records exclusively",
        ],
        "correct": 0,
        "explanation": "Ansible is agentless automation with readable scripts for config, deployment, and orchestration.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Puppet differs from Ansible because Puppet is:",
        "options": [
            "Model-driven and uses agents on devices to maintain configurations",
            "Agentless and script-only with no device-side software",
            "A packet sniffer for Wi-Fi only",
            "A satellite communication protocol",
        ],
        "correct": 0,
        "explanation": "Puppet is model-driven configuration management using agents to enforce desired state.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Configuration management tools perform all EXCEPT:",
        "options": ["Capturing live packets for protocol decode by default", "Automated configuration updates", "Backup and restore of configurations", "Policy enforcement"],
        "correct": 0,
        "explanation": "Config tools (Ansible, Puppet) automate updates, backup/restore, and policy enforcement—not primary packet capture.",
    },
    {
        "lecture": "Lecture 5",
        "question": "SolarWinds Network Performance Monitor is focused on:",
        "options": [
            "Enterprise-grade real-time visibility into performance, availability, and health",
            "Only intrusion prevention inline",
            "Manual cable labeling",
            "MAC address manufacturing",
        ],
        "correct": 0,
        "explanation": "SolarWinds NPM provides enterprise real-time network performance and availability visibility.",
    },
    {
        "lecture": "Lecture 5",
        "question": "ManageEngine OpManager provides:",
        "options": [
            "Real-time monitoring, fault management, and performance analysis",
            "Only DNS caching",
            "Exclusive Bluetooth PAN management",
            "Physical layer signal regeneration",
        ],
        "correct": 0,
        "explanation": "OpManager offers monitoring, fault management, and performance analysis for infrastructure.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Performance management tools analyze primarily:",
        "options": ["Bandwidth, latency, and throughput", "Employee leave schedules", "Desktop wallpaper settings", "Printer font choices"],
        "correct": 0,
        "explanation": "Performance tools focus on bandwidth, latency, throughput, traffic analysis, and capacity planning.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Snort is classified as:",
        "options": ["An IDS/IPS for monitoring traffic and detecting malicious activity", "A configuration backup tool", "A DNS server", "A fiber optic tester"],
        "correct": 0,
        "explanation": "Snort is an intrusion detection/prevention system for real-time malicious activity detection.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Splunk in Lecture 5 is described as:",
        "options": [
            "A SIEM platform collecting and analyzing machine data organization-wide",
            "A simple ping utility only",
            "A VLAN trunking protocol",
            "A twisted-pair cable category",
        ],
        "correct": 0,
        "explanation": "Splunk is a SIEM platform for collecting, analyzing, and visualizing machine/log data.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Security management tools provide functions such as:",
        "options": [
            "Intrusion detection/prevention, log monitoring, and threat analysis",
            "Only VLAN creation without logging",
            "Exclusive DHCP lease assignment",
            "Physical cable crimping guides",
        ],
        "correct": 0,
        "explanation": "Security tools (Snort, Splunk) support IDS/IPS, log monitoring, and threat analysis.",
    },
    {
        "lecture": "Lecture 5",
        "question": "NetFlow Analyzer uses flow technologies such as:",
        "options": ["NetFlow, sFlow, IPFIX, and J-Flow", "Only ICMP echo requests", "Only SMTP message headers", "Infrared remote bursts"],
        "correct": 0,
        "explanation": "NetFlow Analyzer analyzes traffic using flow export technologies like NetFlow, sFlow, IPFIX, J-Flow.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Ntopng provides:",
        "options": [
            "Open-source real-time traffic monitoring and analysis via a web interface",
            "Agentless Ansible playbooks only",
            "On-premises-only satellite uplink control",
            "Exclusive MAC-layer encryption",
        ],
        "correct": 0,
        "explanation": "Ntopng is open-source traffic monitoring/analysis with web-based real-time visibility.",
    },
    {
        "lecture": "Lecture 5",
        "question": "Effective network management in modern enterprises is described as:",
        "options": [
            "A strategic necessity, not optional, for secure efficient scalable reliable networks",
            "Optional for organizations using email only occasionally",
            "Required only for physical cable installation teams",
            "Unrelated to business continuity or security",
        ],
        "correct": 0,
        "explanation": "Lecture 5 concludes effective network management is a strategic necessity where digital infrastructure supports nearly every business function.",
    },
]
